import z from '@deepseek-ai/schemastery';
export declare const WALLPAPER_NS = "wallpaper-engine";
export declare const WallpaperSettingsSchema: z<Schemastery.ObjectS<NoInfer<{
    selectedWallpaperId: z<string, string, "defined">;
    wallpaperDir: z<string, string, "defined">;
    weAssetsDir: z<string, string, "defined">;
    overlayOpacity: z<number, number, "defined">;
    blurEnabled: z<boolean, boolean, "defined">;
    blurRadius: z<number, number, "defined">;
    kenBurns: z<boolean, boolean, "defined">;
    glowEnabled: z<boolean, boolean, "defined">;
    glowThreshold: z<number, number, "defined">;
    glowStrength: z<number, number, "defined">;
    paused: z<boolean, boolean, "defined">;
    pauseOnHidden: z<boolean, boolean, "defined">;
    qualityScale: z<number, number, "defined">;
}>>, Schemastery.ObjectT<NoInfer<{
    selectedWallpaperId: z<string, string, "defined">;
    wallpaperDir: z<string, string, "defined">;
    weAssetsDir: z<string, string, "defined">;
    overlayOpacity: z<number, number, "defined">;
    blurEnabled: z<boolean, boolean, "defined">;
    blurRadius: z<number, number, "defined">;
    kenBurns: z<boolean, boolean, "defined">;
    glowEnabled: z<boolean, boolean, "defined">;
    glowThreshold: z<number, number, "defined">;
    glowStrength: z<number, number, "defined">;
    paused: z<boolean, boolean, "defined">;
    pauseOnHidden: z<boolean, boolean, "defined">;
    qualityScale: z<number, number, "defined">;
}>>, "plain">;
export declare const Config: z<NoInfer<Schemastery.ObjectS<NoInfer<{
    selectedWallpaperId: z<string, string, "defined">;
    wallpaperDir: z<string, string, "defined">;
    weAssetsDir: z<string, string, "defined">;
    overlayOpacity: z<number, number, "defined">;
    blurEnabled: z<boolean, boolean, "defined">;
    blurRadius: z<number, number, "defined">;
    kenBurns: z<boolean, boolean, "defined">;
    glowEnabled: z<boolean, boolean, "defined">;
    glowThreshold: z<number, number, "defined">;
    glowStrength: z<number, number, "defined">;
    paused: z<boolean, boolean, "defined">;
    pauseOnHidden: z<boolean, boolean, "defined">;
    qualityScale: z<number, number, "defined">;
}>>>, NoInfer<Schemastery.ObjectT<NoInfer<{
    selectedWallpaperId: z<string, string, "defined">;
    wallpaperDir: z<string, string, "defined">;
    weAssetsDir: z<string, string, "defined">;
    overlayOpacity: z<number, number, "defined">;
    blurEnabled: z<boolean, boolean, "defined">;
    blurRadius: z<number, number, "defined">;
    kenBurns: z<boolean, boolean, "defined">;
    glowEnabled: z<boolean, boolean, "defined">;
    glowThreshold: z<number, number, "defined">;
    glowStrength: z<number, number, "defined">;
    paused: z<boolean, boolean, "defined">;
    pauseOnHidden: z<boolean, boolean, "defined">;
    qualityScale: z<number, number, "defined">;
}>>>, "volatile">;
